apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ethnic-pheasant-python 
  janus-idp.io/tekton: ethnic-pheasant-python
  backstage.io/kubernetes-id: ethnic-pheasant-python
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: ethnic-pheasant-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  