apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ethnic-pheasant-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ethnic-pheasant-python 
  name: ethnic-pheasant-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ethnic-pheasant-python 
