apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: ethnic-pheasant-python
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:ca1ae040484f92215dd8b2f69e7d1eca50686935@sha256:12aac6b1cc3475063e14fd38864855ce622319a832489148cf207fb2d2acf3c7
        name: container-image  
